[package]
name = "tfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
console = "0.15.10"
reqwest = "0.12.12"
soup = "0.5.1"
tokio = { version = "^1.1.0", features = ["full"] }
